jms_security_extra:
    secure_all_services: false
    expressions: true

security:

    encoders:
        ToDoList\ToDoListBundle\Entity\User:
            algorithm:        sha1
            encode_as_base64: false
            iterations:       1
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        entity_admin:
            memory:
                users:
                    admin: { password: admin, roles: 'ROLE_ADMIN' }
        entity_members:
            entity: { class: ToDoListBundle:User }

# if something gone wrong, reset with the below instructions
#        administrators:
#            entity: { class: ToDoListBundle:User }
#        in_memory:
#            memory:
#                users:
#                    admin: { password: admin, roles: 'ROLE_ADMIN' }
    firewalls:

        login:
            pattern:  ^/user/login$
            security: false
            anonymous: true

        registration:
            pattern:  ^/user/registration$
            security: false
            anonymous: true

        registration_complete:
            pattern:  ^/user/registration-complete$
            security: false
            anonymous: true

        fb_registration:
            pattern:  ^/user/fb-registration$
            security: false
            anonymous: true

        admin_area:
            pattern:    ^/admin
#            anonymous: true
            provider: entity_admin
            http_basic:
                realm: "Area admin"

        secured_area:
            pattern:    ^/.*
            provider: entity_members
            form_login:
                check_path: _user_check_login
                login_path: _user_login
                always_use_default_target_path: true
                default_target_path: /
            logout:
                path:   _user_logout
                target: _index

    access_control:
        - { path: ^/user/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/user/registration, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/user/registration-complete, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/user/fb-registration, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/.*, roles: ROLE_USER }
        - { path: ^/admin, roles: ROLE_ADMIN }